name: finbro
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  flutter_svg: ^0.22.0
  google_nav_bar: ^5.0.6
  flutter_unicons: ^0.0.6
  line_icons: ^2.0.3




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - C:\Users\Tyron\OneDrive\Desktop\FinBro\FinBro\mobile\finbro\assets\address-book-solid.svg
    - C:\Users\Tyron\OneDrive\Desktop\FinBro\FinBro\mobile\finbro\assets\arrow-left-solid.svg
    - C:\Users\Tyron\OneDrive\Desktop\FinBro\FinBro\mobile\finbro\assets\eye-slash-solid.svg
    - C:\Users\Tyron\OneDrive\Desktop\FinBro\FinBro\mobile\finbro\assets\eye-solid.svg
    - C:\Users\Tyron\OneDrive\Desktop\FinBro\FinBro\mobile\finbro\assets\lock-solid.svg
    - C:\Users\Tyron\OneDrive\Desktop\FinBro\FinBro\mobile\finbro\assets\mesh_background.png
    - C:\Users\Tyron\OneDrive\Desktop\FinBro\FinBro\mobile\finbro\assets\paper-plane-solid.svg
    - C:\Users\Tyron\OneDrive\Desktop\FinBro\FinBro\mobile\finbro\assets\house-solid-inactive.svg
    - C:\Users\Tyron\OneDrive\Desktop\FinBro\FinBro\mobile\finbro\assets\house-solid-active.svg
    - C:\Users\Tyron\OneDrive\Desktop\FinBro\FinBro\mobile\finbro\assets\chart-simple-solid-active.svg
    - C:\Users\Tyron\OneDrive\Desktop\FinBro\FinBro\mobile\finbro\assets\chart-simple-solid-inactive.svg
    - C:\Users\Tyron\OneDrive\Desktop\FinBro\FinBro\mobile\finbro\assets\user-solid-active.svg
    - C:\Users\Tyron\OneDrive\Desktop\FinBro\FinBro\mobile\finbro\assets\user-solid-inactive.svg
    - C:\Users\Tyron\OneDrive\Desktop\FinBro\FinBro\mobile\finbro\assets\square-plus-solid.svg
    - C:\Users\Tyron\OneDrive\Desktop\FinBro\FinBro\mobile\finbro\assets\robot-solid-feature-button.svg
    - C:\Users\Tyron\OneDrive\Desktop\FinBro\FinBro\mobile\finbro\assets\chart-pie-solid-feature-button.svg
    - C:\Users\Tyron\OneDrive\Desktop\FinBro\FinBro\mobile\finbro\assets\brain-solid.svg