name: finbro
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  flutter_svg: ^0.22.0
  google_nav_bar: ^5.0.6
  flutter_unicons: ^0.0.6
  line_icons: ^2.0.3
  http: ^1.2.2
  shared_preferences: ^2.3.3
  stomp_dart_client: ^2.1.0
  web_socket_channel: ^3.0.1
  path_provider: ^2.1.5
  permission_handler: ^11.3.1




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
