name: finbro
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.3



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - C:\Users\Tyron\OneDrive\Desktop\FinBro\FinBro\finbro\assets\mesh_background.png
    - C:\Users\Tyron\OneDrive\Desktop\FinBro\FinBro\finbro\assets\address-book-solid.svg
    - C:\Users\Tyron\OneDrive\Desktop\FinBro\FinBro\finbro\assets\eye-slash-solid.svg
    - C:\Users\Tyron\OneDrive\Desktop\FinBro\FinBro\finbro\assets\eye-solid.svg
    - C:\Users\Tyron\OneDrive\Desktop\FinBro\FinBro\finbro\assets\lock-solid.svg
    - C:\Users\Tyron\OneDrive\Desktop\FinBro\FinBro\finbro\assets\paper-plane-solid.svg
    - C:\Users\Tyron\OneDrive\Desktop\FinBro\FinBro\finbro\assets\arrow-left-solid.svg